apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  labels:
    strimzi.io/cluster: my-connect-cluster
  name: github-source-connector
spec:
  class: org.apache.camel.kafkaconnector.github.CamelGithubSourceConnector
  config:
    camel.source.endpoint.oauthToken: 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
    camel.source.endpoint.repoName: ad482-connectors
    camel.source.endpoint.repoOwner: maarten-donderwinkel
    camel.source.path.branchName: main
    camel.source.path.type: event
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    topics: github-events
  tasksMax: 1